const assert=require('assert');
const R=require('./peer-earnings-registry.js');
for(const t of ['VTBR','T','VKCO','OZON','MGNT','LENT']) assert.equal(R.usable(t),false);
assert.equal(R.get('T').reportedValue,650);
assert.equal(R.get('T').comparable,false);
assert.equal(R.get('T').metric,'OPERATING_NET_PROFIT_PER_SHARE_PRO_FORMA_PRE_SPLIT');
assert.equal(R.get('LENT').metric,'NET_PROFIT_ONLY');
assert.equal(R.get('MGNT').verified,true);
assert.equal(R.get('MGNT').comparable,true);
assert.equal(R.get('MGNT').eps,-455.28);
assert.equal(R.get('MGNT').status,'VERIFIED_EXCLUDED');
assert(R.audit('MGNT').missing.includes('positive_eps'));
assert(R.audit('T').missing.includes('comparable_metric'));
assert.equal(R.audit('UNKNOWN').usable,false);
console.log('R1.8.13 exact EPS extraction tests: PASS');
