const assert=require('assert');
const T=require('./trader-decision.js');
const day=(i,base,step,vol=1000)=>{let c=base+i*step;return {begin:new Date(Date.UTC(2026,0,1+i)).toISOString(),open:c-step*.2,high:c+1,low:c-1,close:c,volume:vol}};
const daily=Array.from({length:70},(_,i)=>day(i,100,2,1000+i));
const market=Array.from({length:70},(_,i)=>day(i,200,0.5,5000+i));
const hourly=Array.from({length:60},(_,i)=>{let c=220+i*.6;return {begin:new Date(Date.UTC(2026,8,20,7+i)).toISOString(),open:c-.2,high:c+.3,low:c-.5,close:c,volume:i===59?5000:1000}});
hourly[59].close=hourly[58].high+1;hourly[59].high=hourly[59].close+.2;
let r=T.assess({price:hourly.at(-1).close,daily,hourly,marketDaily:market});
assert.equal(r.verified,true);
assert.equal(r.direction,'LONG');
assert.equal(r.portfolioIndependent,true);
assert(['READY','WAIT'].includes(r.status));
assert(r.score>=10);
assert(Number.isFinite(r.stop)&&Number.isFinite(r.tp1)&&Number.isFinite(r.tp2)&&Number.isFinite(r.tp3));
assert(Number.isFinite(r.rr));
assert.equal(Object.values(r.components).reduce((s,x)=>s+x,0),r.score);
const r2=T.assess({price:hourly.at(-1).close,daily,hourly,marketDaily:market,portfolio:{held:true}});
assert.equal(r2.direction,r.direction);
assert.equal(r2.score,r.score);
r=T.assess({price:100,daily:daily.slice(-10),hourly:hourly.slice(-10),marketDaily:market.slice(-10)});
assert.equal(r.verified,false);
assert.equal(r.direction,'NO_TRADE');
assert(r.missing.includes('D1_60'));
assert.equal(T.grade(16),'A+');assert.equal(T.grade(13),'A');assert.equal(T.grade(10),'B');
console.log('Investor Radar trader decision tests: PASS');
